### ISSUE TITLE
Class constant visibility in Enum

### ISSUE THREAD

**Issue by jdecool** [marc-mabe/php-enum#135]
Actually the `Enum` class only manage `public` constant.

I think it's interesting to manage constant independently of the property visibility.

When I create an Enum, I don't want the developer know how it works internally, so I don't want to expose the constant I used to build it.

Should you open to a PR to make this change ?

**Comment by marc-mabe** [comment]
Hi @jdecool,

Enumerators are public by definition. As PHP doesn't support real enumeration types this library emulates them as much as possible. For that it's using class constants as workaround.

Here are some reasons why enumerators are public:
* enumerators are public by definition as of how they are used
  * by value `MyEnum::ENUMERATOR`
  * by instance `MyEnum::ENUMERATOR()`
* private constants can't be accesses by abstract enum class
* in theory you could have a private/protected enumeration type but this would be class level visibility which is not supported by PHP (like `private class MyEnum extends Enum`).

**Comment by jdecool** [comment]
Thanks for your answer.

But I not agree with you.

The Enum should be encapsulate in the `object` (accessible with `MyEnum::ENUMERATOR()->getValue()`) and should not directly acces the constant `MyEnum::ENUMERATOR` used to build it.

**Comment by marc-mabe** [comment]
Hi @jdecool,

This again is an implementation detail because of the lag of build-in enum support in PHP.
An enumerator is a constant definition.
This implementation uses objects for this case and makes the defined enumerator value and name accessable. On a perfect implementation both information would be available on compile time but that's not possible here as this library emulates the enumeration type as much as possible.
What I want to say is that an enumerator value is just one possible value of a self defined enumeration type. Which makes it public by definition.
